### ISSUE TITLE
error  when loading tc program 'tc_init_e_func'

### ISSUE THREAD

**Issue by zwbrealm** [nothepeople/ONCache#1]
LD_ABS is only allowed in functions that return 'int'.
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

libbpf: -- END LOG --
libbpf: failed to load program 'tc_init_e_func'
libbpf: failed to load object '../tc_prog/tc_prog_kern.o'
Unable to load program
ERR(1): tc cannot attach filter
 Cmdline:tc filter add dev enp65s0f0np0 egress bpf da obj ../tc_prog/tc_prog_kern.o sec tc_init_e
Traceback (most recent call last):
  File "/root/ONCache/user_prog/daemon.py", line 84, in <module>
    init_daemon()
  File "/root/ONCache/user_prog/daemon.py", line 60, in init_daemon
    runcmd(f"./tc_prog_loader --dev {NODE_IFNAME} --filename ../tc_prog/tc_prog_kern.o --sec-name tc_init_e --egress --new-qdisc")
  File "/root/ONCache/user_prog/daemon.py", line 12, in runcmd
    return subprocess.check_output(cmd, shell=True).decode().strip()
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command './tc_prog_loader --dev enp65s0f0np0 --filename ../tc_prog/tc_prog_kern.o --sec-name tc_init_e --egress --new-qdisc' returned non-zero exit status 1.

My kernel is 5.15 ubuntu 22.04, and network interface is Mellonx CX-5

**Comment by zwbrealm** [comment]
ps : 这个错误出现在第三步：cd ~/ONCache/user_prog/; sudo python3 daemon.py，在Step4: Start the ONCache daemon.中

**Comment by shengkai16** [comment]
Hi! Thank you to follow and try out ONCache!

We have never seen this error before and are trying to recurrence it. We want to make sure that are there any errors in Step 1-3? And is *enp65s0f0np0* your kubernetes data plane interface's name (You can check this by `kubectl get nodes -owide`)?

You can also contact my email jefflin@sjtu.edu.cn, and we can try to solve this error together :)
